#!/bin/sh
#
# this is the script run by the Jenkins server to run the build and tests.  Be
# sure to always run it in its dir, i.e. ./run-tests.sh, otherwise it might
# remove things that you don't want it to.

#if [ `dirname $0` != "." ]; then
#    echo "only run this script like ./`basename $0`"
#    exit
#fi

set -e
set -x

if [ -z $WORKSPACE ]; then
    WORKSPACE=`pwd`
fi

#set the mozconfig to be used
cd $WORKSPACE
export MOZCONFIG="$WORKSPACE/external/tor-browser/.mozconfig-android"

#switch to gecko dev and build
cd external/tor-browser
./mach configure
./mach build
./mach package
./mach build-backend -b AndroidEclipse

#------------------------------------------------------------------------------#
# run local tests
cd $WORKSPACE/tests
./run-tests.sh

# only tell jenkins there was an error if we got ERROR or FATAL
[ $(($? & 1)) = "1" ] && exit 1
[ $(($? & 2)) = "2" ] && exit 2
set -e
